### ISSUE TITLE
créer la liste des auteurs

### ISSUE THREAD

**Issue by ms-studio** [eracom-id491/Histoire-de-la-vie#6]
Définir quel élève devra créer quel "chapitre", sur la base de la carte visuelle.

**Comment by ms-studio** [comment]
Bernardo, avez-vous pu attribuer les pages? Ce sera indispensable pour travailler demain.

**Comment by bernardosolid2000** [comment]
Bonjour,

oui j'ai crée un tableau que j'ai envoyer sur le groupe whatsapp, mais je
oublier de vus l'envoyer, mais j'aurais du le faire.

alors le vois-y si joint

**Comment by ms-studio** [comment]
Vous avez répondu par mail, il semble que l'image jointe n'est pas passée.
Vous pouvez l'ajouter ici dans un champ commentaire.
Ou encore mieux: l'ajouter sur https://github.com/eracom-id491/Histoire-de-la-vie avec "Upload file".

**Comment by ms-studio** [comment]
Ça y est, on a le tableau
